### ISSUE TITLE
HTML entities are emitted in SVG which is invalid

### ISSUE THREAD

**Issue by atextor** [jamisonjiang/graph-support#1]
When the text of an element contains a character for which an HTML entity exists, this entity appears in the SVG output, even though this is not valid. HTML entities are not defined there; renderers/browsers will complain that they are not. For example, if the text contains "ü", the SVG output contains "\&uuml;". Instead,
* it should instead contain the literal character ü, _or_
* it should instead contain "\&#252;", _or_
* a DOCTYPE with the corresponding entity definition needs to be added, i.e., put the following between the `<?xml` tag and the `<svg` tag: `<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [ <!ENTITY uuml "&#252;"> ]>`

To reproduce:

The following code:
```java
public class Test {
   public static void main( final String[] args ) throws ExecuteException {
      final Graphviz graphviz = Graphviz.digraph()
            .addNode( Node.builder().label( "ü" ).build() )
            .build();
      System.out.println( graphviz.toSvgStr() );
   }
}
```

creates:
```svg
<?xml version="1.0" encoding="UTF-8"?>
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
 height="116.0pt" width="94.0pt" viewBox="0.00 0.00 94.0 116.0"><g id="graph_root"
class="graph" transform="scale(1.0 1.0) rotate(0)"><g id="graph_0" class="graph">
<polygon id="graph_root_polygon" fill="#ffffff" points="0.0,0.0 94.0,0.0 94.0,116.0 0.0,
116.0 0.0,0.0"></polygon></g><g id="node_0" class="node"><ellipse id="node_0_ellipse" 
cx="47.0" cy="58.0" rx="27.0" ry="18.0" fill="none" stroke="#000000"></ellipse>
<text id="node_0_text_0" x="47.875" y="62.666666666666664" text-anchor="middle" 
font-size="14.0" fill="#000000">&uuml;</text></g></g></svg>
```

**Comment by jamisonjiang** [comment]
@atextor Thanks for your feedback, it will be fixed in the next release.

**Comment by jamisonjiang** [comment]
Done in 1.1.5
