### ISSUE TITLE
Table alignment problems, depending on font

### ISSUE THREAD

**Issue by atextor** [jamisonjiang/graph-support#2]
I'm trying to create a Node based on a table, with left-aligned lines. However, even with `.align(Labeljust.LEFT)`, I can't seem to create consistently aligned lines. The results vary depending on the used font.

Creation of the node:
```java
String fontName = "...";
Html.Table table = table()
   .border( 1 )
   .cellBorder( 0 )
   .cellSpacing( 0 )
   .cellPadding( 4 )
   .tr( td().text( "Test test test" ).fontName( fontName ).align( Labeljust.CENTER ) )
   .tr( td().text( "Another test test" ).fontName( fontName ).align( Labeljust.CENTER ) )
   .tr( td().cellPadding( 1 ).bgColor( Color.BLACK ).height( 1 ) )
   .tr( td().text( "someProperty: Test test123" ).fontName( fontName ).align( Labeljust.LEFT ) )
   .tr( td().text( "description: This is a test description" ).fontName( fontName ).align( Labeljust.LEFT ) )
   .tr( td().text( "anotherProperty: Another12" ).fontName( fontName ).align( Labeljust.LEFT ) )
   .tr( td().text( "see: http://example.com/" ).fontName( fontName ).align( Labeljust.LEFT ) )
   .tr( td().text( "yetAnother: yetAnotherTest" ).fontName( fontName ).align( Labeljust.LEFT ) );
Node node = Node.builder().color( Color.BLACK ).table( table ).build();
```

The results, for various fonts tried:
_Roboto Condensed_:
![image](https://github.com/jamisonjiang/graph-support/assets/1199036/a3a62b30-2d04-48a8-8253-9eac9ca335f1)

_Arial_:
![image](https://github.com/jamisonjiang/graph-support/assets/1199036/103d4774-1bba-44ac-8314-bf3be0e879c5)

_Noto Sans_:
![image](https://github.com/jamisonjiang/graph-support/assets/1199036/ba01ae58-fadf-410b-9a7c-333de5ccd306)

_DejaVu Sans_:
![image](https://github.com/jamisonjiang/graph-support/assets/1199036/5925e7ef-1e97-4351-8d5e-70585568627c)

Is there something I can do to force multiple lines to be properly left aligned?

**Comment by jamisonjiang** [comment]
This is a known issue in the schedule task. The font from svg needs to be mapped with the font from java.awt, otherwise there will be some errors when measuring the text length.

**Comment by atextor** [comment]
I tried the following:

```java
// java.io.File
// java.awt.Font
// java.awt.GraphicsEnvironment
File fontFile = new File("RobotoCondensed.ttf");
Font font = Font.createFont(Font.TRUETYPE_FONT, fontFile);
GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
ge.registerFont(font);
```

to make the font known to AWT before generating the SVG, but unfortunately it made no difference.

**Comment by jamisonjiang** [comment]
1. Please take it from the font name below:
```java
String[] fonts = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
for (String f : fonts) {
  System.out.println(f);
}
```
2.Please confirm whether the machine that browses the svg is the same as the machine that generated the svg. The fonts of different machines may not be the same, and the results of the svg generated on the server to the svg renderer of different machines may be different.

**Comment by atextor** [comment]
I have tried that as well (before explictly registering the font in the AWT GraphicsEnvironment). `getAvailableFontFamilyNames()` contains all the fonts all the font names I've tried in the generation. I'm doing all tests locally, i.e, the machine generating the SVG is the same machine that is viewing the SVG.

**Comment by jamisonjiang** [comment]
I can not reproduce on my local env, would you mind provide env info and font output?

**Comment by atextor** [comment]
I'm running Ubuntu Linux 20.04.5, with Xfce 4.14. Adoptium/Temurin JDK 17.0.8.
The output of `GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames()` has over 2000 entries on my machine, but it contains the fonts:

![image](https://github.com/jamisonjiang/graph-support/assets/1199036/79df159a-5339-44d4-98cf-8f3c5e18c8f4)

Please let me know if there is other specific info that would help you.

**Comment by jamisonjiang** [comment]
This problem is due to the inaccurate measurement of `FontMetrics` in some fonts. At present, I have not found a better way to measure the length of the string. If you have any local more accurate test methods, you can register the implementation of `MeasureText` locally to override someone's. method to measure the length of the string, or you can try to use the font with the most accurate measurement.

**Comment by jamisonjiang** [comment]
We supported export image directly in latest version and the more accuracy font name detect because render and measure at the same way.

**Comment by jamisonjiang** [comment]
1.3.1 most flexible font family select policy
