### ISSUE TITLE
Different font sizes, tooltips and HTML links?

### ISSUE THREAD

**Issue by kovzol** [jamisonjiang/graph-support#6]
Hi, it would be great if there would be support for tooltips and HTML links. Something like

https://dreampuf.github.io/GraphvizOnline/#strict%20digraph%20G%20%7B%0Anode%20%5Bshape%20%3D%20box%2C%20color%20%3D%20black%2C%20style%20%3D%20filled%5D%3B%0Aedge%20%5Bdir%20%3D%20back%5D%3B%0A1%20-%3E%20%22G%20is%20the%20midpoint%20of%20DE%22%3B%0A1%20-%3E%202%3B%0A2%20-%3E%203%3B%0A3%20-%3E%20%22F%20is%20the%20midpoint%20of%20CB%22%3B%0A3%20-%3E%20%22DC%20%20%E2%8A%A5%20%20DB%22%3B%0A2%20-%3E%204%3B%0A4%20-%3E%20%22F%20is%20the%20midpoint%20of%20CB%22%3B%0A4%20-%3E%20%22EC%20%20%E2%8A%A5%20%20EB%22%3B%0A1%20%5B%20label%3D%3C1)%20FG%20%20%E2%8A%A5%20%20DE%3CBR%2F%3E%0A%3CFONT%20POINT-SIZE%3D%2210%22%3E8.%20sz.%3C%2FFONT%3E%3E%2C%20fillcolor%20%3D%20%22%23C0FFFF%22%2C%0Atooltip%3D%228.%20szab%C3%A1ly%3A%20Pitagorasz-t%C3%A9tel%22%2C%20URL%3D%22https%3A%2F%2Fgithub.com%2Fkovzol%2FJava-Geometry-Expert%2Fblob%2Fmaster%2Fsrc%2Fdocs%2Fhelp%2Fimages_a%2Frectangle.gif%22%5D%3B%0A2%20%5B%20label%20%3D%20%222)%20FD%20%3D%20FE%22%2C%20fillcolor%20%3D%20%22%23FFA0A0%22%5D%3B%0A3%20%5B%20label%20%3D%20%223)%20CF%20%3D%20DF%22%2C%20fillcolor%20%3D%20%22%23C0FFFF%22%5D%3B%0A4%20%5B%20label%20%3D%20%224)%20CF%20%3D%20EF%22%2C%20fillcolor%20%3D%20%22%23C0FFFF%22%5D%3B%0A%22G%20is%20the%20midpoint%20of%20DE%22%20%5B%20fillcolor%20%3D%20%22%23F7CAC9%22%2C%20shape%20%3D%20oval%2C%20style%20%3D%20filled%20%5D%3B%0A%22F%20is%20the%20midpoint%20of%20CB%22%20%5B%20fillcolor%20%3D%20%22%23F7CAC9%22%2C%20shape%20%3D%20oval%2C%20style%20%3D%20filled%20%5D%3B%0A%22DC%20%20%E2%8A%A5%20%20DB%22%20%5B%20fillcolor%20%3D%20%22%23F7CAC9%22%2C%20shape%20%3D%20oval%2C%20style%20%3D%20filled%20%5D%3B%0A%22F%20is%20the%20midpoint%20of%20CB%22%20%5B%20fillcolor%20%3D%20%22%23F7CAC9%22%2C%20shape%20%3D%20oval%2C%20style%20%3D%20filled%20%5D%3B%0A%22EC%20%20%E2%8A%A5%20%20EB%22%20%5B%20fillcolor%20%3D%20%22%23F7CAC9%22%2C%20shape%20%3D%20oval%2C%20style%20%3D%20filled%20%5D%3B%0A%7D

which uses different font sizes in a node, a tooltip, and a HTML link. Please advise me further if this is possible in the library, and if not, is there hope to support it.

Thank you in advance.

**Comment by jamisonjiang** [comment]
Similar effect use table feature
```java
    Color COFFFF = Color.ofRGB("#C0FFFF");
    Node n1 = Node.builder()
        .shape(NodeShapeEnum.PLAIN)
        .table(
            table()
                .border(1)
                .cellBorder(0)
                .cellSpacing(0)
                .cellPadding(6)
                .tr(td().bgColor(COFFFF).text("1) FG  ⊥  DE"))
                .tr(td().bgColor(COFFFF).text("8. sz.").fontSize(10)
                        .href("https://github.com/kovzol/Java-Geometry-Expert/blob/master/src/docs/help/images_a/rectangle.gif"))
        )
        .build();
    Node n2 = Node.builder().label("2) FD = FE").fillColor(Color.ofRGB("#FFA0A0")).build();
    Node n3 = Node.builder().label("3) CF = DF").build();
    Node n4 = Node.builder().label("4) CF = EF").build();
    Node n5 = Node.builder().label("G is the midpoint of DE").build();
    Node n7 = Node.builder().label("DC  ⊥  DB").build();
    Node n8 = Node.builder().label("F is the midpoint of CB").build();
    Node n9 = Node.builder().label("EC  ⊥  EB").build();

    Graphviz graphviz = Graphviz.digraph()
        .tempNode(Node.builder().shape(NodeShapeEnum.RECT).color(Color.BLACK).fillColor(Color.ofRGB("#C0FFFF")).build())
        .tempLine(Line.tempLine().dir(Dir.BACK).build())
        .addLine(n1, n5)
        .addLine(n1, n2)
        .addLine(n2, n3)
        .addLine(n3, n8)
        .addLine(n3, n7)
        .addLine(n2, n4)
        .addLine(n4, n8)
        .addLine(n4, n9)
        .startSub()
        .tempNode(Node.builder().fillColor(Color.ofRGB("#F7CAC9")).shape(NodeShapeEnum.ELLIPSE).build())
        .addNode(n5, n7, n8, n9)
        .endSub()
        .build();
```
![image](https://github.com/jamisonjiang/graph-support/assets/125274994/c2242d83-82bd-4bf9-b967-c461e3c967ee)

**Comment by kovzol** [comment]
Wonderful, thanks for the quick response!
Is it also possible to add a tooltip?

**Comment by jamisonjiang** [comment]
tooltips is not supported now I will add in the future and you can implement by following approach:
### Insert tooltips element by original svg String;
you can assign table unique id then get this element by this id from svg document, then insert tooltips attribute manually:
```java
    Node n1 = Node.builder()
        .shape(NodeShapeEnum.PLAIN)
        .table(
            table()
                .id("tool_tip_node_id")
                .border(1)
                .bgColor(COFFFF)
                .cellBorder(0)
                .cellSpacing(0)
                .cellPadding(6)
                .href("https://github.com/kovzol/Java-Geometry-Expert/blob/master/src/docs/help/images_a/rectangle.gif")
                .tr(td().color(COFFFF).text("1) FG  ⊥  DE"))
                .tr(td().color(COFFFF).text("8. sz.").fontSize(10))
        )
        .build();
```
![image](https://github.com/jamisonjiang/graph-support/assets/125274994/b91a55f1-2add-4fe1-861b-252e27d3943d)
![image](https://github.com/jamisonjiang/graph-support/assets/125274994/1d6b7b12-1b31-4b14-a04a-922932fb004d)

**Comment by kovzol** [comment]
Thanks, wonderful!

**Comment by kovzol** [comment]
Here is a stable look of a GraphViz output: https://matek.hu/zoltan/blog-20240730.php (please see item 7). Can this be done in graph-support? If not or not yet, please let me know. I would be happy to contribute some code to make this achievable unless you can do the improvements in reasonable time. Thank you.

**Comment by jamisonjiang** [comment]
> Here is a stable look of a GraphViz output: https://matek.hu/zoltan/blog-20240730.php (please see item 7). Can this be done in graph-support? If not or not yet, please let me know. I would be happy to contribute some code to make this achievable unless you can do the improvements in reasonable time. Thank you.

The trapezoid and triangle in the picture do exist, but they are in opposite directions.
I am currently working on the next version of the test. These two shapes can be considered and will not take up too much time. However, if you have more shape requirements, I am also happy to receive your PR. Adding a shape only requires a simple formula to describe some characteristics of the shape and add a drawing function.

**Comment by jamisonjiang** [comment]
@kovzol Please check the latest version:[1.4.0](https://github.com/jamisonjiang/graph-support/releases/tag/1.4.0) and I give you an example for your requirement
```java
    Color COFFFF = Color.ofRGB("#C0FFFF");
    Node n1 = Node.builder()
        .shape(NodeShapeEnum.INVTRIANGLE)
        .table(
            table()
                .border(0)
                .bgColor(COFFFF)
                .cellBorder(0)
                .cellSpacing(0)
                .cellPadding(6)
                .href("https://github.com/kovzol/Java-Geometry-Expert/blob/master/src/docs/help/images_a/rectangle.gif")
                .tooltip("8. szabály: Pitagorasz-tétel")
                .tr(td().color(COFFFF).text("1) FG  ⊥  DE"))
                .tr(td().color(COFFFF).text("8. sz.").fontSize(10))
        )
        .href("https://github.com/kovzol/Java-Geometry-Expert/blob/master/src/docs/help/images_a/rectangle.gif")
        .tooltip("8. szabály: Pitagorasz-tétel")
        .build();
    Node n2 = Node.builder().label("2) FD = FE").fillColor(Color.ofRGB("#FFA0A0")).build();
    Node n3 = Node.builder().label("3) CF = DF").build();
    Node n4 = Node.builder().label("4) CF = EF").build();
    Node n5 = Node.builder().label("G is the midpoint of DE").build();
    Node n7 = Node.builder().label("DC  ⊥  DB").build();
    Node n8 = Node.builder().label("F is the midpoint of CB").build();
    Node n9 = Node.builder().label("EC  ⊥  EB").build();

    Graphviz graphviz = Graphviz.digraph()
        .tempNode(Node.builder().shape(NodeShapeEnum.RECT).color(Color.BLACK).fillColor(COFFFF).build())
        .tempLine(Line.tempLine().dir(Dir.BACK).build())
        .addLine(n1, n5)
        .addLine(n1, n2)
        .addLine(n2, n3)
        .addLine(n3, n8)
        .addLine(n3, n7)
        .addLine(n2, n4)
        .addLine(n4, n8)
        .addLine(n4, n9)
        .startSub()
        .tempNode(Node.builder().fillColor(Color.ofRGB("#F7CAC9")).shape(NodeShapeEnum.ELLIPSE).build())
        .addNode(n5, n7, n8, n9)
        .endSub()
        .build();
```
![image](https://github.com/user-attachments/assets/eddda5fd-85c2-47da-8556-840f996d9dab)

And if you have any interesting to contribute any other node shapes, please check: [NodeShape](https://github.com/jamisonjiang/graph-support/blob/main/src/main/java/org/graphper/api/attributes/NodeShape.java)

**Comment by kovzol** [comment]
Thanks so much, I will check it out soon.

**Comment by kovzol** [comment]
Thanks again, it works indeed nicely.
One question: I cannot convince batik to show the tooltip and to visit the HTML link. Do you have an idea?

**Comment by jamisonjiang** [comment]
@kovzol graph-support use xlink:title is part of the SVG 1.1 specification to implement tooltip, but Apache Batik does not natively support it, so you can write any replacement program change to 1.0 version
1.1
```svg
<a xlink:href="https://github.com/kovzol/Java-Geometry-Expert/blob/master/src/docs/help/images_a/rectangle.gif" target="_blank" xlink:title="8. szabály: Pitagorasz-tétel">
<polygon id="node_0_polygon" points="67.0,106.0 40.0,70.0 94.0,70.0" fill="#C0FFFF" stroke="#000000"></polygon>
</a>
```
to
1.0
```svg
<a xlink:href="https://github.com/kovzol/Java-Geometry-Expert/blob/master/src/docs/help/images_a/rectangle.gif" target="_blank">
<title>8. szabály: Pitagorasz-tétel</title>
<polygon id="node_0_polygon" points="67.0,106.0 40.0,70.0 94.0,70.0" fill="#C0FFFF" stroke="#000000"></polygon>
</a>
```

For html link I think you should implement yourself listener for mouse click event and  wake up browser by  `java.awt.Desktop.getDesktop().browse(new java.net.URI(href));`

```java
    JSVGCanvas svgCanvas = new JSVGCanvas();
    svgCanvas.setDocumentState(JSVGCanvas.ALWAYS_DYNAMIC);

    // Add listener to detect when SVG rendering is complete
    svgCanvas.addGVTTreeRendererListener(new GVTTreeRendererAdapter() {
      @Override
      public void gvtRenderingCompleted(GVTTreeRendererEvent e) {
        // Add mouse listener for handling clicks
        svgCanvas.addMouseListener(new MouseAdapter() {
          @Override
          public void mouseClicked(MouseEvent e) {
            Point point = e.getPoint();
            SVGDocument svgDocument = svgCanvas.getSVGDocument();
            // recognize the element based on event coordinate and extract the href then call va.awt.Desktop.getDesktop().browse(new java.net.URI(href))
          }
        });
      }
    });
```

**Comment by kovzol** [comment]
For the record: here is the new version of JGEX which extensively uses graph-support 1.4: https://github.com/kovzol/Java-Geometry-Expert/releases/tag/0.86. Thanks again! :-)
